#!/bin/bash -eu

announce () {
    echo ''
    echo "$1"
    echo '============================================================'
}

git_describe () {
    tags=$(git tag -l)

    if [ -z "$tags" ]; then
        echo '0.0.0'
        return
    fi

    tag=$(git describe --abbrev=0)
    echo "${tag:1}"
}

script=$(readlink -f "${BASH_SOURCE[0]}")
directory=$(dirname "$script")
cd "$directory"

export DOTNET_CLI_TELEMETRY_OPTOUT='1'

runtimes=('linux-x64' 'win-x64')
version=$(git_describe)

announce 'Cleanup'
git clean -dfX

announce 'Build'
cd 'src'
dotnet build -warnaserror

announce 'Test'
dotnet test

for runtime in "${runtimes[@]}"; do
    announce "Publish $runtime $version"
    dotnet publish 'Chunkyard' -o '../artifacts' -p:Version="$version" -p:ContinuousIntegrationBuild=true -r "$runtime" -p:PublishSingleFile=true -p:PublishTrimmed=true -p:DebugType=none
done
