#!/bin/bash -eu

announce () {
    echo ''
    echo "$1"
    echo '============================================================'
}

cd "$(dirname "$BASH_SOURCE")"

export DOTNET_CLI_TELEMETRY_OPTOUT='1'

announce 'Build'
rm -rf 'artifacts'
dotnet build -p:TreatWarningsAsErrors=true

announce 'Test'
dotnet test

announce 'Publish'
dotnet publish 'Chunkyard' -p:ContinuousIntegrationBuild=true --runtime linux-x64
