[package]
name = "chunker"
version = "0.1.0"
authors = ["Florian Winkelbauer <mail@florianwinkelbauer.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fastcdc = "1.0.2"
