<Project>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AnalysisMode>All</AnalysisMode>
    <MSTestAnalysisMode>All</MSTestAnalysisMode>
    <EnableMSTestRunner>true</EnableMSTestRunner>
    <ArtifactsPath>$(MSBuildThisFileDirectory)../artifacts</ArtifactsPath>
    <CheckForOverflowUnderflow>true</CheckForOverflowUnderflow>
    <DebugType>embedded</DebugType>
    <PublishSingleFile>true</PublishSingleFile>
    <PublishTrimmed>true</PublishTrimmed>
  </PropertyGroup>

</Project>
